max_width = 80
hard_tabs = false
tab_spaces = 4
brace_style = "SameLineWhere"
fn_args_layout = "Compressed"
fn_params_layout = "Compressed"
align_after_open_bracket = true
control_brace_style = "AlwaysSameLine"
comment_width = 80
empty_item_single_line = true
format_macro_matchers = false
fn_sig_newline = "Never"
